theme = "term16_dark" 

[keys.normal]
Cmd-d=":bc"
Cmd-S-d=":bco"
Cmd-S-minus="collapse_selection"
Cmd-s=":write"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[editor]
line-number = "relative"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape] 
insert = "bar"
