theme = "term16_dark" 

[keys.normal]
C-d=":bc"
C-S-d=":bco"
C-S-minus="collapse_selection"
C-s = ":write"
C-w = "expand_selection"

[editor]
line-number = "relative"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.auto-save]
focus-lost = true
after-delay.enable = true
